{
  "openapi": "3.1.0",
  "info": {
    "title": "Awake Automation API",
    "version": "1.0.0"
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/v1/app/status": {
      "get": {
        "operationId": "status",
        "summary": "Status",
        "x-cli": {
          "command": [
            "status"
          ],
          "bindings": {}
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StatusResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "x-capabilities": [
          "running-app"
        ]
      }
    },
    "/v1/app/show": {
      "post": {
        "operationId": "show",
        "summary": "Show",
        "x-cli": {
          "command": [
            "show"
          ],
          "bindings": {}
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ShowResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "x-capabilities": [
          "running-app"
        ]
      }
    },
    "/v1/app/quit": {
      "post": {
        "operationId": "quit",
        "summary": "Quit",
        "x-cli": {
          "command": [
            "quit"
          ],
          "bindings": {}
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QuitResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "x-capabilities": [
          "running-app"
        ]
      }
    },
    "/v1/configuration": {
      "get": {
        "operationId": "configList",
        "summary": "Config list",
        "x-cli": {
          "command": [
            "config",
            "list"
          ],
          "bindings": {
            "query.all": {
              "option": "--all"
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConfigListResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "all",
            "in": "query",
            "required": false,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "x-capabilities": []
      }
    },
    "/v1/configuration/{key}": {
      "get": {
        "operationId": "configGet",
        "summary": "Config get",
        "x-cli": {
          "command": [
            "config",
            "get"
          ],
          "bindings": {
            "path.key": {
              "argument": 0
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConfigGetResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "key",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-capabilities": []
      },
      "put": {
        "operationId": "configSet",
        "summary": "Config set",
        "x-cli": {
          "command": [
            "config",
            "set"
          ],
          "bindings": {
            "path.key": {
              "argument": 0
            },
            "body.value": {
              "option": "--value"
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConfigSetResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "key",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ConfigSetBody"
              }
            }
          }
        },
        "x-capabilities": []
      },
      "delete": {
        "operationId": "configUnset",
        "summary": "Config unset",
        "x-cli": {
          "command": [
            "config",
            "unset"
          ],
          "bindings": {
            "path.key": {
              "argument": 0
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConfigUnsetResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "key",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "x-capabilities": []
      }
    },
    "/v1/configuration/reload": {
      "post": {
        "operationId": "configReload",
        "summary": "Config reload",
        "x-cli": {
          "command": [
            "config",
            "reload"
          ],
          "bindings": {}
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConfigReloadResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "x-capabilities": []
      }
    },
    "/v1/configuration/validate": {
      "post": {
        "operationId": "configValidate",
        "summary": "Config validate",
        "x-cli": {
          "command": [
            "config",
            "validate"
          ],
          "bindings": {
            "body.content": {
              "option": "--content"
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operation completed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ConfigValidateResult"
                }
              }
            }
          },
          "default": {
            "description": "Operation failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResult"
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ConfigValidateBody"
              }
            }
          }
        },
        "x-capabilities": []
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "AppConfigurationValue": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "string"
          },
          {
            "type": "integer"
          }
        ]
      },
      "Message": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "required": [
          "message"
        ],
        "additionalProperties": false
      },
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "details": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        },
        "required": [
          "code",
          "message"
        ],
        "additionalProperties": false
      },
      "ErrorResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "error": {
            "$ref": "#/components/schemas/Error"
          }
        },
        "required": [
          "error"
        ],
        "additionalProperties": false
      },
      "AppConfigurationEntry": {
        "type": "object",
        "properties": {
          "key": {
            "$ref": "#/components/schemas/AppConfigurationKey"
          },
          "value": {
            "$ref": "#/components/schemas/AppConfigurationValue"
          },
          "source": {
            "$ref": "#/components/schemas/AppConfigurationSource"
          },
          "documentation": {
            "type": "string"
          }
        },
        "required": [
          "key",
          "value",
          "source",
          "documentation"
        ]
      },
      "AppConfigurationKey": {
        "type": "string",
        "enum": [
          "show-welcome-message",
          "api-host",
          "api-port"
        ]
      },
      "AppConfigurationSource": {
        "type": "string",
        "enum": [
          "defaults",
          "user"
        ]
      },
      "ConfigurationReport": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string"
          },
          "entries": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AppConfigurationEntry"
            }
          }
        },
        "required": [
          "path",
          "entries"
        ],
        "additionalProperties": false
      },
      "ValidationReport": {
        "type": "object",
        "properties": {
          "valid": {
            "type": "boolean"
          }
        },
        "required": [
          "valid"
        ],
        "additionalProperties": false
      },
      "AppStatus": {
        "type": "object",
        "properties": {
          "appName": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "processIdentifier": {
            "type": "integer"
          },
          "isFrontmost": {
            "type": "boolean"
          }
        },
        "required": [
          "appName",
          "version",
          "processIdentifier",
          "isFrontmost"
        ]
      },
      "StatusResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/AppStatus"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ShowResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/Message"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "QuitResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/Message"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ConfigListResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/ConfigurationReport"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ConfigGetResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/AppConfigurationEntry"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ConfigSetResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/AppConfigurationEntry"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ConfigSetBody": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          }
        },
        "required": [
          "value"
        ],
        "additionalProperties": false
      },
      "ConfigUnsetResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/AppConfigurationEntry"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ConfigReloadResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/ValidationReport"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ConfigValidateResult": {
        "type": "object",
        "properties": {
          "requestId": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/ValidationReport"
          }
        },
        "required": [
          "requestId",
          "data"
        ],
        "additionalProperties": false
      },
      "ConfigValidateBody": {
        "type": "object",
        "properties": {
          "content": {
            "type": "string"
          }
        },
        "required": [],
        "additionalProperties": false
      }
    }
  }
}
